// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClHDiuPhBHgN5jUa4MiE5M2Efi4JTmouc',
    appId: '1:366487651612:web:dffa1895221869e02c66d9',
    messagingSenderId: '366487651612',
    projectId: 'biddingsystem-a9d3c',
    authDomain: 'biddingsystem-a9d3c.firebaseapp.com',
    storageBucket: 'biddingsystem-a9d3c.firebasestorage.app',
    measurementId: 'G-DJ7FJ4MCG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACXsk32250cLUqVz5WEm2JTabbjnKsnAY',
    appId: '1:366487651612:android:f93ecbc3ecd9e3392c66d9',
    messagingSenderId: '366487651612',
    projectId: 'biddingsystem-a9d3c',
    storageBucket: 'biddingsystem-a9d3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_ydSeUBGac9uWTwiEbQTZUsfvgLLK5os',
    appId: '1:366487651612:ios:371b2ed190b2cb062c66d9',
    messagingSenderId: '366487651612',
    projectId: 'biddingsystem-a9d3c',
    storageBucket: 'biddingsystem-a9d3c.firebasestorage.app',
    iosClientId: '366487651612-phrotmdl6fthhntovkol7c7is1g0t4p1.apps.googleusercontent.com',
    iosBundleId: 'com.example.antique',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_ydSeUBGac9uWTwiEbQTZUsfvgLLK5os',
    appId: '1:366487651612:ios:371b2ed190b2cb062c66d9',
    messagingSenderId: '366487651612',
    projectId: 'biddingsystem-a9d3c',
    storageBucket: 'biddingsystem-a9d3c.firebasestorage.app',
    iosClientId: '366487651612-phrotmdl6fthhntovkol7c7is1g0t4p1.apps.googleusercontent.com',
    iosBundleId: 'com.example.antique',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClHDiuPhBHgN5jUa4MiE5M2Efi4JTmouc',
    appId: '1:366487651612:web:c1c69d25326276262c66d9',
    messagingSenderId: '366487651612',
    projectId: 'biddingsystem-a9d3c',
    authDomain: 'biddingsystem-a9d3c.firebaseapp.com',
    storageBucket: 'biddingsystem-a9d3c.firebasestorage.app',
    measurementId: 'G-P19CBBM715',
  );
}
